---
name: prisma
description: |
  The prisma formatter that is powered by prisma engines.
homepage: https://github.com/prisma
licenses:
  - Apache-2.0
languages:
  - Prisma
categories:
  - Formatter

source:
  id: pkg:npm/prisma@4.14.0

bin:
  prisma: npm:prisma
